name: MSBuild.AdditionalBuilds.CI 


resources:
- repo: self
  clean: true


jobs:
- template: build.yml  
  parameters:
   name: macOS
   artifactFileName: '$(Build.ArtifactStagingDirectory)/macOS.zip'
   pool:
     name: 'Hosted macOS'

- template: build.yml  
  parameters:
    name: Windows
    artifactFileName: '$(Build.ArtifactStagingDirectory)/Windows.zip'
    pool:
      name: 'Hosted VS2017'
