name: MSBuild.AdditionalBuilds.CI 


resources:
- repo: self
  clean: true


jobs:
- template: build.yml  
  parameters:
   name: macOS
   artifactName: NuGetPackages-MacOS
   pool:
     name: 'Hosted macOS'

- template: build.yml  
  parameters:
    name: Windows
    artifactName: NuGetPackages-Windows
    pool:
      name: 'Hosted VS2017'
