parameters:
  name: ''
  pool: ''
  nugetVersion: 4.6.2
  sdkVersion: 2.2.102
  artifactName: ''

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  steps:
  - task: NuGetToolInstaller@0
    displayName: 'Use NuGet'
    inputs:
      versionSpec: ${{ parameters.nugetVersion }}


  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core'
    inputs:
      version: ${{ parameters.sdkVersion }}


  - task: PowerShell@2
    inputs: 
      filePath: build_and_tests.ps1
      workingDirectory: ./
      arguments: Debug

    displayName: 'restore & build Debug'

  - task: PowerShell@2
    inputs: 
      filePath: build_and_tests.ps1
      workingDirectory: ./
      arguments: Release

    displayName: 'restore & build Release'

  # - task: ArchiveFiles@2
  #   displayName: 'Archive $(Build.SourcesDirectory)'
  #   inputs:
  #     rootFolderOrFile: '$(Build.SourcesDirectory)'

  #     archiveFile: ${{ parameters.artifactFileName }} 

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'dir'
      workingDirectory: $(Build.SourcesDirectory)/drop/Release
    displayName: 'Output of Filesystem'
    

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: NuGet Packages'
    inputs:
      PathtoPublish: $(Build.SourcesDirectory)/drop/Release/*.nupkg
      artifactType: container
      ArtifactName: ${{parameters.artifactName}}
